/**
 * Rules Engine Infrastructure
 * Comprehensive rule processing system with validation, execution, and precedence management
 */

import { z } from 'zod';
import { Lead, UccFiling } from '@shared/schema';
import { db } from '../db';
import { sql } from 'drizzle-orm';

/**
 * Rule types enumeration
 */
export enum RuleType {
  VALIDATION = 'validation',
  SCORING = 'scoring',
  TRANSFORMATION = 'transformation',
  ENRICHMENT = 'enrichment',
  ALERT = 'alert'
}

/**
 * Rule precedence levels (higher value = higher priority)
 */
export enum RulePrecedence {
  AI_SUGGESTED = 10,
  HEURISTIC = 20,
  LEARNED_ML = 30,
  TENANT_CUSTOMER = 40,
  ADMIN = 50
}

/**
 * Logical operators for conditions
 */
export enum LogicalOperator {
  AND = 'AND',
  OR = 'OR',
  NOT = 'NOT'
}

/**
 * Comparison operators for conditions
 */
export enum ComparisonOperator {
  EQUALS = '==',
  NOT_EQUALS = '!=',
  GREATER_THAN = '>',
  LESS_THAN = '<',
  GREATER_THAN_OR_EQUAL = '>=',
  LESS_THAN_OR_EQUAL = '<=',
  CONTAINS = 'contains',
  NOT_CONTAINS = 'not_contains',
  IN = 'in',
  NOT_IN = 'not_in',
  REGEX_MATCH = 'regex',
  IS_NULL = 'is_null',
  IS_NOT_NULL = 'is_not_null'
}

/**
 * Condition interface for rule evaluation
 */
export interface RuleCondition {
  id: string;
  field: string;
  operator: ComparisonOperator;
  value: any;
  dataType?: 'string' | 'number' | 'boolean' | 'date' | 'array';
}

/**
 * Composite condition with logical operators
 */
export interface CompositeCondition {
  id: string;
  operator: LogicalOperator;
  conditions: (RuleCondition | CompositeCondition)[];
}

/**
 * Action to be executed when rule matches
 */
export interface RuleAction {
  type: 'set_field' | 'add_score' | 'multiply_score' | 'send_alert' | 'enrich_data' | 'transform' | 'reject' | 'approve';
  field?: string;
  value?: any;
  score?: number;
  message?: string;
  metadata?: Record<string, any>;
}

/**
 * Rule definition interface
 */
export interface Rule {
  id: string;
  name: string;
  description: string;
  type: RuleType;
  precedence: RulePrecedence;
  priority: number; // Within precedence level (0-100)
  enabled: boolean;
  condition: RuleCondition | CompositeCondition;
  actions: RuleAction[];
  tags?: string[];
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: string;
  version: number;
}

/**
 * Rule execution context
 */
export interface RuleContext {
  lead?: Lead;
  uccFilings?: UccFiling[];
  scores: Record<string, number>;
  transformations: Record<string, any>;
  alerts: Alert[];
  enrichments: Record<string, any>;
  metadata: Record<string, any>;
  executionPath: string[];
  timing: Record<string, number>;
}

/**
 * Alert generated by rule execution
 */
export interface Alert {
  ruleId: string;
  ruleName: string;
  severity: 'info' | 'warning' | 'error' | 'critical';
  message: string;
  timestamp: Date;
  context?: Record<string, any>;
}

/**
 * Rule execution result
 */
export interface RuleExecutionResult {
  ruleId: string;
  ruleName: string;
  matched: boolean;
  executionTime: number;
  actionsExecuted: RuleAction[];
  errors?: string[];
  warnings?: string[];
  transformations?: Record<string, any>;
  scoreImpact?: number;
}

/**
 * Rule conflict detection result
 */
export interface RuleConflict {
  rule1: Rule;
  rule2: Rule;
  conflictType: 'field_override' | 'score_conflict' | 'action_conflict' | 'condition_overlap';
  description: string;
  severity: 'low' | 'medium' | 'high';
  resolution?: string;
}

/**
 * Rule validation result
 */
export interface RuleValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
  suggestions: string[];
}

/**
 * Rules Engine main class
 */
export class RulesEngine {
  private rules: Map<string, Rule> = new Map();
  private rulesByType: Map<RuleType, Set<string>> = new Map();
  private rulesByPrecedence: Map<RulePrecedence, Set<string>> = new Map();
  private executionCache: Map<string, RuleExecutionResult> = new Map();

  constructor() {
    // Initialize type and precedence maps
    Object.values(RuleType).forEach(type => {
      this.rulesByType.set(type, new Set());
    });
    Object.values(RulePrecedence).forEach(precedence => {
      this.rulesByPrecedence.set(precedence as RulePrecedence, new Set());
    });
  }

  /**
   * Add or update a rule
   */
  public addRule(rule: Rule): RuleValidationResult {
    const validation = this.validateRule(rule);
    if (!validation.valid) {
      return validation;
    }

    this.rules.set(rule.id, rule);
    this.rulesByType.get(rule.type)?.add(rule.id);
    this.rulesByPrecedence.get(rule.precedence)?.add(rule.id);
    this.clearCache();

    return validation;
  }

  /**
   * Remove a rule
   */
  public removeRule(ruleId: string): boolean {
    const rule = this.rules.get(ruleId);
    if (!rule) return false;

    this.rules.delete(ruleId);
    this.rulesByType.get(rule.type)?.delete(ruleId);
    this.rulesByPrecedence.get(rule.precedence)?.delete(ruleId);
    this.clearCache();

    return true;
  }

  /**
   * Get a rule by ID
   */
  public getRule(ruleId: string): Rule | undefined {
    return this.rules.get(ruleId);
  }

  /**
   * Get all rules
   */
  public getAllRules(): Rule[] {
    return Array.from(this.rules.values());
  }

  /**
   * Get rules by type
   */
  public getRulesByType(type: RuleType): Rule[] {
    const ruleIds = this.rulesByType.get(type) || new Set();
    return Array.from(ruleIds).map(id => this.rules.get(id)!).filter(Boolean);
  }

  /**
   * Execute rules against a context
   */
  public async execute(context: RuleContext, types?: RuleType[]): Promise<RuleExecutionResult[]> {
    const results: RuleExecutionResult[] = [];
    const rulesToExecute = this.getSortedRules(types);

    for (const rule of rulesToExecute) {
      if (!rule.enabled) continue;

      const startTime = Date.now();
      const result = await this.executeRule(rule, context);
      result.executionTime = Date.now() - startTime;
      
      results.push(result);
      context.executionPath.push(`${rule.name} (${result.matched ? 'matched' : 'skipped'})`);
      context.timing[rule.id] = result.executionTime;

      // Apply transformations to context
      if (result.transformations) {
        Object.assign(context.transformations, result.transformations);
      }
    }

    return results;
  }

  /**
   * Execute a single rule
   */
  private async executeRule(rule: Rule, context: RuleContext): Promise<RuleExecutionResult> {
    const result: RuleExecutionResult = {
      ruleId: rule.id,
      ruleName: rule.name,
      matched: false,
      executionTime: 0,
      actionsExecuted: [],
      errors: [],
      warnings: []
    };

    try {
      // Evaluate condition
      const matched = this.evaluateCondition(rule.condition, context);
      result.matched = matched;

      if (matched) {
        // Execute actions
        for (const action of rule.actions) {
          try {
            await this.executeAction(action, rule, context);
            result.actionsExecuted.push(action);
          } catch (error) {
            result.errors?.push(`Action execution failed: ${error instanceof Error ? error.message : String(error)}`);
          }
        }
      }
    } catch (error) {
      result.errors?.push(`Rule evaluation failed: ${error instanceof Error ? error.message : String(error)}`);
    }

    return result;
  }

  /**
   * Evaluate a condition against context
   */
  private evaluateCondition(condition: RuleCondition | CompositeCondition, context: RuleContext): boolean {
    if ('operator' in condition && condition.operator in LogicalOperator) {
      // Composite condition
      const composite = condition as CompositeCondition;
      switch (composite.operator) {
        case LogicalOperator.AND:
          return composite.conditions.every(c => this.evaluateCondition(c, context));
        case LogicalOperator.OR:
          return composite.conditions.some(c => this.evaluateCondition(c, context));
        case LogicalOperator.NOT:
          return !this.evaluateCondition(composite.conditions[0], context);
        default:
          return false;
      }
    } else {
      // Simple condition
      const simple = condition as RuleCondition;
      const fieldValue = this.getFieldValue(simple.field, context);
      return this.compareValues(fieldValue, simple.operator, simple.value, simple.dataType);
    }
  }

  /**
   * Get field value from context
   */
  private getFieldValue(field: string, context: RuleContext): any {
    const parts = field.split('.');
    let value: any = context;

    for (const part of parts) {
      if (value && typeof value === 'object' && part in value) {
        value = value[part];
      } else {
        return undefined;
      }
    }

    return value;
  }

  /**
   * Compare values based on operator
   */
  private compareValues(
    fieldValue: any, 
    operator: ComparisonOperator, 
    compareValue: any, 
    dataType?: string
  ): boolean {
    // Type coercion based on dataType
    if (dataType === 'number') {
      fieldValue = Number(fieldValue);
      compareValue = Number(compareValue);
    } else if (dataType === 'date') {
      fieldValue = new Date(fieldValue);
      compareValue = new Date(compareValue);
    }

    switch (operator) {
      case ComparisonOperator.EQUALS:
        return fieldValue === compareValue;
      case ComparisonOperator.NOT_EQUALS:
        return fieldValue !== compareValue;
      case ComparisonOperator.GREATER_THAN:
        return fieldValue > compareValue;
      case ComparisonOperator.LESS_THAN:
        return fieldValue < compareValue;
      case ComparisonOperator.GREATER_THAN_OR_EQUAL:
        return fieldValue >= compareValue;
      case ComparisonOperator.LESS_THAN_OR_EQUAL:
        return fieldValue <= compareValue;
      case ComparisonOperator.CONTAINS:
        return String(fieldValue).includes(String(compareValue));
      case ComparisonOperator.NOT_CONTAINS:
        return !String(fieldValue).includes(String(compareValue));
      case ComparisonOperator.IN:
        return Array.isArray(compareValue) && compareValue.includes(fieldValue);
      case ComparisonOperator.NOT_IN:
        return Array.isArray(compareValue) && !compareValue.includes(fieldValue);
      case ComparisonOperator.REGEX_MATCH:
        return new RegExp(compareValue).test(String(fieldValue));
      case ComparisonOperator.IS_NULL:
        return fieldValue === null || fieldValue === undefined;
      case ComparisonOperator.IS_NOT_NULL:
        return fieldValue !== null && fieldValue !== undefined;
      default:
        return false;
    }
  }

  /**
   * Execute an action
   */
  private async executeAction(action: RuleAction, rule: Rule, context: RuleContext): Promise<void> {
    switch (action.type) {
      case 'set_field':
        if (action.field && action.value !== undefined) {
          this.setFieldValue(action.field, action.value, context);
        }
        break;

      case 'add_score':
        if (action.field && action.score !== undefined) {
          context.scores[action.field] = (context.scores[action.field] || 0) + action.score;
        }
        break;

      case 'multiply_score':
        if (action.field && action.score !== undefined) {
          context.scores[action.field] = (context.scores[action.field] || 0) * action.score;
        }
        break;

      case 'send_alert':
        context.alerts.push({
          ruleId: rule.id,
          ruleName: rule.name,
          severity: action.metadata?.severity || 'info',
          message: action.message || `Alert from rule: ${rule.name}`,
          timestamp: new Date(),
          context: action.metadata
        });
        break;

      case 'enrich_data':
        if (action.field && action.value !== undefined) {
          context.enrichments[action.field] = action.value;
        }
        break;

      case 'transform':
        if (action.field && action.value !== undefined) {
          context.transformations[action.field] = action.value;
        }
        break;

      case 'reject':
        context.metadata.rejected = true;
        context.metadata.rejectionReason = action.message || rule.name;
        break;

      case 'approve':
        context.metadata.approved = true;
        context.metadata.approvalReason = action.message || rule.name;
        break;
    }
  }

  /**
   * Set field value in context
   */
  private setFieldValue(field: string, value: any, context: RuleContext): void {
    const parts = field.split('.');
    let target: any = context;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!(part in target) || typeof target[part] !== 'object') {
        target[part] = {};
      }
      target = target[part];
    }

    target[parts[parts.length - 1]] = value;
  }

  /**
   * Validate a rule
   */
  public validateRule(rule: Rule): RuleValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
    const suggestions: string[] = [];

    // Validate basic properties
    if (!rule.id) errors.push('Rule ID is required');
    if (!rule.name) errors.push('Rule name is required');
    if (!rule.type) errors.push('Rule type is required');
    if (!rule.precedence) errors.push('Rule precedence is required');
    if (rule.priority < 0 || rule.priority > 100) {
      errors.push('Rule priority must be between 0 and 100');
    }

    // Validate condition
    if (!rule.condition) {
      errors.push('Rule condition is required');
    } else {
      this.validateCondition(rule.condition, errors, warnings);
    }

    // Validate actions
    if (!rule.actions || rule.actions.length === 0) {
      warnings.push('Rule has no actions defined');
    } else {
      rule.actions.forEach((action, index) => {
        this.validateAction(action, index, errors, warnings);
      });
    }

    // Check for conflicts with existing rules
    const conflicts = this.detectConflicts(rule);
    if (conflicts.length > 0) {
      conflicts.forEach(conflict => {
        if (conflict.severity === 'high') {
          errors.push(`Conflict with rule "${conflict.rule2.name}": ${conflict.description}`);
        } else if (conflict.severity === 'medium') {
          warnings.push(`Potential conflict with rule "${conflict.rule2.name}": ${conflict.description}`);
        } else {
          suggestions.push(`Minor overlap with rule "${conflict.rule2.name}": ${conflict.description}`);
        }
      });
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
      suggestions
    };
  }

  /**
   * Validate a condition
   */
  private validateCondition(
    condition: RuleCondition | CompositeCondition, 
    errors: string[], 
    warnings: string[]
  ): void {
    if ('operator' in condition && condition.operator in LogicalOperator) {
      // Composite condition
      const composite = condition as CompositeCondition;
      if (!composite.conditions || composite.conditions.length === 0) {
        errors.push('Composite condition must have at least one sub-condition');
      } else {
        composite.conditions.forEach(c => this.validateCondition(c, errors, warnings));
      }
    } else {
      // Simple condition
      const simple = condition as RuleCondition;
      if (!simple.field) errors.push('Condition field is required');
      if (!simple.operator) errors.push('Condition operator is required');
      if (simple.operator !== ComparisonOperator.IS_NULL && 
          simple.operator !== ComparisonOperator.IS_NOT_NULL && 
          simple.value === undefined) {
        errors.push(`Condition value is required for operator ${simple.operator}`);
      }
    }
  }

  /**
   * Validate an action
   */
  private validateAction(action: RuleAction, index: number, errors: string[], warnings: string[]): void {
    if (!action.type) {
      errors.push(`Action ${index + 1}: type is required`);
    }

    switch (action.type) {
      case 'set_field':
      case 'transform':
      case 'enrich_data':
        if (!action.field) errors.push(`Action ${index + 1}: field is required`);
        if (action.value === undefined) errors.push(`Action ${index + 1}: value is required`);
        break;
      
      case 'add_score':
      case 'multiply_score':
        if (!action.field) errors.push(`Action ${index + 1}: field is required`);
        if (action.score === undefined) errors.push(`Action ${index + 1}: score is required`);
        break;
      
      case 'send_alert':
        if (!action.message) warnings.push(`Action ${index + 1}: alert message is recommended`);
        break;
    }
  }

  /**
   * Detect conflicts between rules
   */
  public detectConflicts(newRule: Rule): RuleConflict[] {
    const conflicts: RuleConflict[] = [];

    for (const existingRule of this.rules.values()) {
      if (existingRule.id === newRule.id) continue;

      // Check for field override conflicts
      const fieldConflicts = this.detectFieldConflicts(newRule, existingRule);
      if (fieldConflicts) conflicts.push(fieldConflicts);

      // Check for condition overlap
      const conditionOverlap = this.detectConditionOverlap(newRule, existingRule);
      if (conditionOverlap) conflicts.push(conditionOverlap);

      // Check for score conflicts
      const scoreConflicts = this.detectScoreConflicts(newRule, existingRule);
      if (scoreConflicts) conflicts.push(scoreConflicts);
    }

    return conflicts;
  }

  /**
   * Detect field conflicts between rules
   */
  private detectFieldConflicts(rule1: Rule, rule2: Rule): RuleConflict | null {
    const fields1 = new Set<string>();
    const fields2 = new Set<string>();

    // Extract fields modified by each rule
    rule1.actions.forEach(action => {
      if (action.field && ['set_field', 'transform'].includes(action.type)) {
        fields1.add(action.field);
      }
    });

    rule2.actions.forEach(action => {
      if (action.field && ['set_field', 'transform'].includes(action.type)) {
        fields2.add(action.field);
      }
    });

    // Check for overlapping fields
    const overlap = Array.from(fields1).filter(f => fields2.has(f));
    if (overlap.length > 0) {
      return {
        rule1,
        rule2,
        conflictType: 'field_override',
        description: `Both rules modify fields: ${overlap.join(', ')}`,
        severity: rule1.precedence === rule2.precedence ? 'high' : 'medium',
        resolution: 'Consider different field names or adjust rule precedence'
      };
    }

    return null;
  }

  /**
   * Detect condition overlap between rules
   */
  private detectConditionOverlap(rule1: Rule, rule2: Rule): RuleConflict | null {
    // This is a simplified overlap detection
    // In production, you'd want more sophisticated logic
    if (rule1.type === rule2.type && rule1.precedence === rule2.precedence) {
      const fields1 = this.extractConditionFields(rule1.condition);
      const fields2 = this.extractConditionFields(rule2.condition);
      
      const overlap = fields1.filter(f => fields2.includes(f));
      if (overlap.length > 0) {
        return {
          rule1,
          rule2,
          conflictType: 'condition_overlap',
          description: `Rules have overlapping conditions on fields: ${overlap.join(', ')}`,
          severity: 'low',
          resolution: 'Review conditions to ensure they do not conflict'
        };
      }
    }

    return null;
  }

  /**
   * Extract fields from a condition
   */
  private extractConditionFields(condition: RuleCondition | CompositeCondition): string[] {
    const fields: string[] = [];

    if ('operator' in condition && condition.operator in LogicalOperator) {
      const composite = condition as CompositeCondition;
      composite.conditions.forEach(c => {
        fields.push(...this.extractConditionFields(c));
      });
    } else {
      const simple = condition as RuleCondition;
      if (simple.field) fields.push(simple.field);
    }

    return fields;
  }

  /**
   * Detect score conflicts between rules
   */
  private detectScoreConflicts(rule1: Rule, rule2: Rule): RuleConflict | null {
    const scores1 = new Set<string>();
    const scores2 = new Set<string>();

    rule1.actions.forEach(action => {
      if (action.field && ['add_score', 'multiply_score'].includes(action.type)) {
        scores1.add(action.field);
      }
    });

    rule2.actions.forEach(action => {
      if (action.field && ['add_score', 'multiply_score'].includes(action.type)) {
        scores2.add(action.field);
      }
    });

    const overlap = Array.from(scores1).filter(s => scores2.has(s));
    if (overlap.length > 0) {
      return {
        rule1,
        rule2,
        conflictType: 'score_conflict',
        description: `Both rules affect scores: ${overlap.join(', ')}`,
        severity: 'medium',
        resolution: 'Ensure score modifications are complementary'
      };
    }

    return null;
  }

  /**
   * Get sorted rules by precedence and priority
   */
  private getSortedRules(types?: RuleType[]): Rule[] {
    let rules = Array.from(this.rules.values());

    // Filter by type if specified
    if (types && types.length > 0) {
      rules = rules.filter(r => types.includes(r.type));
    }

    // Sort by precedence (descending) then priority (descending)
    return rules.sort((a, b) => {
      if (a.precedence !== b.precedence) {
        return b.precedence - a.precedence;
      }
      return b.priority - a.priority;
    });
  }

  /**
   * Clear execution cache
   */
  private clearCache(): void {
    this.executionCache.clear();
  }

  /**
   * Export rules to JSON
   */
  public exportRules(): string {
    const rules = Array.from(this.rules.values());
    return JSON.stringify(rules, null, 2);
  }

  /**
   * Import rules from JSON
   */
  public importRules(json: string): RuleValidationResult[] {
    const results: RuleValidationResult[] = [];
    
    try {
      const rules = JSON.parse(json) as Rule[];
      for (const rule of rules) {
        const result = this.addRule(rule);
        results.push(result);
      }
    } catch (error) {
      results.push({
        valid: false,
        errors: [`Failed to parse JSON: ${error instanceof Error ? error.message : String(error)}`],
        warnings: [],
        suggestions: []
      });
    }

    return results;
  }
}

// Export singleton instance
export const rulesEngine = new RulesEngine();